baseURL = "https://kommodeskab.github.io/SocialProjectWebsite/"
title = "Computational Social Science Project (Group 2)"
description = "A project in 02467 Computational Social Science (2024) in connectivity of global airports and text analysis of their reviews."
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Andreas Bagge", "Gustav Rørhauge", "Rasmus Sørensen"]
    notebook = "https://github.com/kommodeskab/SocialProject"
    data = "https://github.com/kommodeskab/SocialProject"
    github = "https://github.com/kommodeskab/SocialProjecte"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

